version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # porta usada pelo cliente .NET
      - "15672:15672" # porta do painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  producer:
    build:
      context: ./Producer
      dockerfile: dockerfile
    container_name: producer
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
  consumer:
    build:
      context: ./Consumer
      dockerfile: dockerfile
    container_name: consumer   
    depends_on:
      - rabbitmq

